# Generated by Django 3.0.8 on 2020-07-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Arponblog', max_length=255),
        ),
    ]
