# Generated by Django 3.0.8 on 2020-07-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogy', '0003_auto_20200722_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='ecommerce', max_length=255),
        ),
    ]
